### ISSUE TITLE
Xpdf is failing to maintain extra space between the two words in the sentence 

### ISSUE THREAD

**Issue by amit2303angaitkar** [kermitt2/xpdf-4.00#6]
Hi , 
I have to parse the pdf through the Xpdf library . When I am extracting the data from xpdf library , it is failing to maintain extra space in between the two words in the sentence . Xpdf is remove the extra space in between the two words.

please look into this .

Thanks & Regards 

Amit Angaitkar

**Comment by kermitt2** [comment]
Hello @amit2303angaitkar 

For question about the xpdf library, please contact the auteur of the project: http://www.xpdfreader.com/

Here is only a mirror/fork of xpdf for convenience of using git module for building [pdfalto](https://github.com/kermitt2/pdfalto/).
